### ISSUE TITLE
Europe!

### ISSUE THREAD

**Issue by ghost** [wrr/wwwhisper#10]
I guess not an issue but would be great to see this add on available in Europe

**Comment by vassyz** [comment]
Any updates on this?

**Comment by silpol** [comment]
@vassyz what do you mean "available in Europe"? It is available already from here to everywhere in plain source code with instructions how to build. What else you need?

**Comment by vassyz** [comment]
wwwhisper is currently only available in the US region as a [Heroku add-on](https://addons.heroku.com/wwwhisper). This should have been made clearer by the author.

**Comment by wrr** [comment]
It took a long time, but EU based back-end for the Heroku add-on is finally available: https://elements.heroku.com/addons/wwwhisper
