### ISSUE TITLE
Heroku app rename action is not supported

### ISSUE THREAD

**Issue by karol-lotkowski** [wrr/wwwhisper#17]
After renaming Heroku app wwwhisper add-on stooped work correctly.

By opening Heroku app in the browser I got message:
Invalid request URL, you can use wwwhisper admin to allow requests from this address.

Add-on admin panel (...wwwhisper/admin/) also was not available.

I had to remove and add add-on once again to make it work and have access to the admin panel.

**Comment by wrr** [comment]
This is pretty difficult to solve. To correctly handle Mozilla Persona authentication, wwwhisper needs to know URLs that are used to access the app. Unfortunately, when an app is renamed, Heroku does not sent information about this to add-ons that the app uses. The only solution that works right now, is to use wwwhispe/admin panel before the rename (so using an old URL) to add a new URL. But a user would need to somehow know and remember about this, which is unrealistic.

**Comment by parthnaik** [comment]
Hi, I am facing this same issue in 2020. Is the only solution to disable and recreate wwwhisper for the new renamed application for it to work properly?

**Comment by wrr** [comment]
This is no longer an issue, wwwhisper is now switched to a new version of the Heroku add-on API and when app URL changes, the change is automatically detected and requests from new URL are allowed.
