### ISSUE TITLE
Update to django-browserid 1.0.0

### ISSUE THREAD

**Issue by edrex** [wrr/wwwhisper#18]
I'm trying to package wwwhisper for Arch Linux and (Arch being Arch) it packages the latest django-browserid. Any reason wwwhisper still uses 0.10.1?

**Comment by edrex** [comment]
each of the releases between 0.10.1 and 1.0.0 claim backward compatibility, so I'm going to try with the current release and see if anything breaks.

**Comment by wrr** [comment]
Thank you for reporting this. There was no particular reason for using 0.10.1, 1.0.0 works well and it is now allowed in requirements.txt.
