### ISSUE TITLE
Getting Logged In Email Address

### ISSUE THREAD

**Issue by nbaki** [wrr/wwwhisper#25]
I'm using WWWhisper in my RoR application, but I want to know if there's a way to get the user's email that was used to log-in through whisper? Is there someway I can hook into the whisper layer from within my app to get this information?

**Comment by wrr** [comment]
The user email is available in `request.env['REMOTE_USER']`.

**Comment by wrr** [comment]
Please reopen if you encounter any problems with the `REMOTE_USER`.
